name: Create Android Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.1)'
        required: true
        default: '1.0.0'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Update version in build.gradle
      run: |
        sed -i "s/versionName \".*\"/versionName \"${{ github.event.inputs.version }}\"/" android/app/build.gradle
        # Increment version code
        CURRENT_CODE=$(grep "versionCode" android/app/build.gradle | sed 's/.*versionCode \([0-9]*\).*/\1/')
        NEW_CODE=$((CURRENT_CODE + 1))
        sed -i "s/versionCode $CURRENT_CODE/versionCode $NEW_CODE/" android/app/build.gradle
        echo "Updated to version ${{ github.event.inputs.version }} with code $NEW_CODE"

    - name: Trigger Android Build
      uses: ./.github/workflows/android-compile.yml
      with:
        build_type: release
    
    - name: Spaghetti Kart v${{ github.event.inputs.version }}
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Spaghetti Kart v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        body: |
          ## 🏎️ Spaghetti Kart v${{ github.event.inputs.version }}
          
          ### What's New
          - Improved folder selection with SAF (Storage Access Framework)
          - Automatic mods syncing from user folder
          - Better UI with rounded dialogs
          - Torch app integration for easy mk64.o2r creation
          
          ### Installation
          1. Download the APK below
          2. Install on your Android device
          3. Enable "Install from unknown sources" in Android settings
          4. Select a folder for your game files
          5. Add your mk64.o2r file (use Torch app to create from ROM)
          6. Enjoy!
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: 🏎️ Spaghetti Kart v${{ github.event.inputs.version }}
        body: |
          ## 🏎️ Spaghetti Kart v${{ github.event.inputs.version }}
          
          ### 📱 Android Release
          
          **✨ Highlights:**
          - ⚡ Optimized release build with R8 code shrinking
          - 📦 Reduced APK size and improved performance
          - 🗂️ Enhanced file management with SAF integration
          
          ### 🛠️ Changes
          - 🧭 Improved folder selection with SAF (Storage Access Framework)
          - 🔁 Automatic mods syncing from user folder
          - 🧊 Better UI with rounded dialogs
          - 🔥 Torch app integration for easy mk64.o2r creation
          
          ### 📥 Installation
          1. ⬇️ Download the APK below
          2. 📲 Install on your Android device
          3. 🔓 Enable "Install from unknown sources" in Android settings
          4. 📁 Select a folder for your game files
          5. 💾 Add your mk64.o2r file (use Torch app to create from ROM)
          6. 🎮 Enjoy!

    - name: Upload Release APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./spaghettikart-release.apk
        asset_name: SpaghettiKart-v${{ github.event.inputs.version }}-release.apk
        asset_content_type: application/vnd.android.package-archive
