name: Windows Validation

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        config: [Release, Debug]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - name: Build
        run: |
          cmake -S . -B "build/x64" -G "Visual Studio 17 2022" -T v143 -A x64 -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          cmake --build ./build/x64 --config ${{ matrix.config }} --parallel 10
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: spaghetti-windows-${{ matrix.config }}
          path: ./build/x64/${{ matrix.config }}
          retention-days: 1
